export const Labels: {[key: string]: string} = {
    user: 'کاربر',
    role: 'نقش',
    group: 'گروه کاربری',
    permission: 'قابلیت زیرسامانه',
    action: 'سرویس',
    subsystem: 'زیرسامانه',
    description: 'توضیحات',
    create: 'ایجاد',
    update: 'ویرایش',
    delete: 'حذف',
    deActive: 'غیرفعالسازی',
    enabled: 'وضعیت',
    name: 'نام',
    title: 'عنوان',
    url: 'آدرس (url)',
    id: 'شناسه',
    version: 'نسخه',
    actions: 'سرویس ها',
    active: 'فعال',
    inactive: 'غیرفعال',
    permissions: 'قابلیت های سامانه',
    users: 'کاربران',
    subsystems: 'زیرسامانه ها',
    operations: 'عملیات',
    mng: 'مدیریت',
    yes: 'بله',
    no: 'خیر',
    find: 'جست‌وجو',
    view: 'مشاهده',
    back: 'بازگشت',
    real: 'نوع کاربر',
    legalUser: 'حقوقی',
    realUser: 'حقیقی',
    userName: 'نام کاربری',
    firstName: 'نام',
    password: 'رمز عبور',
    lastName: 'نام خانوادگی',
    mobileNumber: 'شماره موبایل',
    roles: 'نقش ها',
    groups: 'گروه های کاربری',
    reset: 'بازنشانی',
    row: 'ردیف',
    assign: 'افزودن',
    confirm: 'تایید',
    basicInfo: 'اطلاعات',
    searchParams: 'فیلترهای جست‌وجوی',
    cancel: 'انصراف',
    submit: 'ثبت',
  changePassword: 'تغییر رمز عبور',
  assigned: 'برگزیده'
}
